Adding the recipient to the ERC20BalanceGteEnforcer terms
MetaMask/delegation-framework pull request #38
Opened 2024-12-16 17:25 UTC by hanzel98

### **What?**

- 

### **Why?**

- 

### **How?**

-

2024-12-16 18:06 UTC, dylandesrosier approved these changes

2025-03-07 16:15 UTC, McOso commented on broadcast/DeployEnvironmentSetUp.s.sol/59141/run-1734402606.json
We can probably leave out the broadcast

2025-03-07 16:17 UTC, McOso commented on src/enforcers/ERC20BalanceGteEnforcer.sol
> +     * are the address of the token, the next 32 bytes are the amount the balance should be greater than
```suggestion
     * is the address of the token, the next 32 bytes is the amount of tokens the balance should be greater than or equal to
```

2025-03-07 16:18 UTC, McOso commented on src/enforcers/ERC20BalanceGteEnforcer.sol
> +     * @param _terms 72 packed bytes where: the first 20 bytes are the address of the recipient, the next 20 bytes
```suggestion
     * @param _terms 72 packed bytes where: the first 20 bytes is the address of the recipient, the next 20 bytes
```

2025-03-07 16:19 UTC, McOso approved these changes

2025-03-07 16:20 UTC, McOso requested changes
This needs to be updated off v1.2.0 or later. Including the execution mode modifier

2025-03-07 21:10 UTC, hanzel98 commented on broadcast/DeployEnvironmentSetUp.s.sol/59141/run-1734402606.json
I reverted the change

2025-03-07 21:12 UTC, hanzel98 commented on src/enforcers/ERC20BalanceGteEnforcer.sol
> +     * are the address of the token, the next 32 bytes are the amount the balance should be greater than
sure

2025-03-07 21:12 UTC, hanzel98 commented on src/enforcers/ERC20BalanceGteEnforcer.sol
> +     * @param _terms 72 packed bytes where: the first 20 bytes are the address of the recipient, the next 20 bytes
sure

2025-03-07 22:30 UTC, McOso approved these changes

2025-03-08 01:47 UTC, merged